language: scala

scala:
  - 2.11.12

sudo: false

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xms1024M package

scripts:
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

